[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Kendo"
authors = [{name = "Tsuyoshi", email = "ariga@usp.br"}]
dynamic = ["version", "description"]
